FROM flink:latest

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install redis elasticsearch apache-flink

WORKDIR /opt/flink/job

USER flink

CMD ["flink", "run", "-py", "flink_process.py"]